### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by miodragma** [bergben/ng2-img-max#11]
When i use universal for ssr i have this error:
/node_modules/bergben-pica/dist/bundles/bergben-pica.umd.js:120
        window.pica = exports;
ReferenceError: window is not defined

**Comment by bergben** [comment]
Hey @miodragma . Can you run npm update and then try again? It should be fixed with bergben-pica@2.0.27 
I am not sure if it all works correctly though...

**Comment by reactionic127** [comment]
@miodragma 
I have a same problem when I install the module.
did you fixed it?

**Comment by miodragma** [comment]
@reactionic127 
no i didn't fix yet

@bergben 
stil i have error but now the problem is TypeError: Cannot set property 'pica' of undefined
and now this problem is on:  ng serve
i remove 
if (typeof window !== 'undefined') {
 +            var window = {};
 +        }
from dist/bergben-pica.js and ng serve is working for now,  but with ssr when i run node server.js is the same error: window is not defined or with update bergben-pica@2.0.28 TypeError: Cannot set property 'pica' of undefined .

**Comment by bergben** [comment]
can you try again with 2.0.29 ? I failed to update some part of the code yesterday sorry.

**Comment by miodragma** [comment]
now ng serve is working as before that is OK, but on run ssr
node_modules/ng2-img-max/dist/src/ng2-img-max.service.js:10
import { Injectable, Inject, forwardRef } from '@angular/core';
SyntaxError: Unexpected token import

**Comment by bergben** [comment]
I undid the changes as they introduced some other issues.
The solution to this problem would be to fix this issue: https://github.com/bergben/ng2-pica/issues/3 I think.
I don't have much time currently so I probably won't be able to fix it for a few weeks...

**Comment by hiepxanh** [comment]
What about this:
![image](https://user-images.githubusercontent.com/16970990/31392577-da2271c4-ae03-11e7-8c06-deeff483ed88.png)

[Universal Jquery](https://github.com/angular/universal#universal-gotchas)

**Comment by bergben** [comment]
@hiepxanh that's exactly what I mean. The current version of the official pica does not use the window var anymore, my one year old fork of it however still does...

**Comment by bergben** [comment]
version 2.1.6 should fix this issue. The underlying pica library is now a direct dependency to the official package. @miodragma @reactionic127 @hiepxanh  :)
